name: Acknowledge Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  acknowledge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Post acknowledgement comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `Thanks for opening this pull request.
              Iâ€™ve received it and will review the changes shortly.'
            });
